Update README.md
ddevdan/monitoria-es-2022-2 pull request #38
Opened 2022-12-29 13:00 UTC by MarcoAntonioAndradeMO

Adicionando meu nome na lista.

2022-12-29 14:42 UTC, ddevdan requested changes
Tem um conflito, poderia resolver

2022-12-29 14:42 UTC, ddevdan commented on README.md
> +- Luiz Phillip Pereira Barbosa
Tem um conflito aqui, poderia resolver por favor? @MarcoAntonioAndradeMO

2022-12-29 19:12 UTC, MarcoAntonioAndradeMO commented on README.md
> +- Luiz Phillip Pereira Barbosa
Acho que consegui resolver, deu certo ?

2023-01-02 21:13 UTC, MarcoAntonioAndradeMO commented
ainda tem algum conflito ?

2023-01-02 22:22 UTC, ddevdan approved these changes

2023-01-02 22:23 UTC, merged